# Generated by Django 4.0.6 on 2022-07-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=64)),
                ('visited', models.IntegerField(default=0)),
                ('deals', models.IntegerField(default=0)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
